name: Bug Report
description: Report something that isn't working
title: "[bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Steps to reproduce
    validations:
      required: true
  - type: dropdown
    id: role
    attributes:
      label: Role
      options:
        - Admin
        - Student
        - Accountant
        - Admissions
        - Academic
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App version
    validations:
      required: true
